# Generated by Django 2.1.2 on 2019-03-05 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offernewsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featuredpost',
            name='position',
            field=models.CharField(choices=[(2, 'Cover_Big'), (1, 'Cover_Small'), (0, 'First_Page')], default=0, max_length=15),
        ),
        migrations.AlterField(
            model_name='post',
            name='offerType',
            field=models.CharField(choices=[(0, 'Deal'), (1, 'Coupon')], default=0, max_length=1),
        ),
    ]
