# Generated by Django 2.1.2 on 2019-02-15 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offernewsapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='branch',
            field=models.ForeignKey(default=1, on_delete=None, to='offernewsapp.Branch'),
            preserve_default=False,
        ),
    ]
