# Generated by Django 2.1.2 on 2019-01-28 19:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('offernewsapp', '0002_auto_20190128_1811'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalAd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=100)),
                ('position', models.CharField(choices=[('P', 'Popup'), ('F', 'Front_Page')], default='F', max_length=1)),
                ('featuredExpireDate', models.DateField()),
                ('featuredDate', models.DateField(auto_now_add=True)),
                ('isActive', models.BooleanField(db_index=True, default=True)),
                ('price', models.PositiveIntegerField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExternalAdPricing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(choices=[('P', 'Popup'), ('F', 'Front_Page')], default='F', max_length=1)),
                ('price', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='advertise',
            name='advertiser',
        ),
        migrations.RemoveField(
            model_name='advertise',
            name='price',
        ),
        migrations.DeleteModel(
            name='FeaturedPosition',
        ),
        migrations.RemoveField(
            model_name='featurepricing',
            name='durationType',
        ),
        migrations.RemoveField(
            model_name='featurepricing',
            name='priceAmount',
        ),
        migrations.AddField(
            model_name='featured',
            name='position',
            field=models.CharField(choices=[('CB', 'Cover_Big'), ('CS', 'Cover_Small'), ('FF', 'First_Page')], default='FF', max_length=2),
        ),
        migrations.AddField(
            model_name='featured',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='featurepricing',
            name='position',
            field=models.CharField(choices=[('CB', 'Cover_Big'), ('CS', 'Cover_Small'), ('FF', 'First_Page')], default='FF', max_length=2),
        ),
        migrations.AddField(
            model_name='featurepricing',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='AdPricing',
        ),
        migrations.DeleteModel(
            name='Advertise',
        ),
    ]
