# Generated by Django 2.1.2 on 2019-01-28 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('offernewsapp', '0004_auto_20190128_2030'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedCom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(choices=[('C', 'Com_Page'), ('F', 'First_Page')], default='F', max_length=1)),
                ('featuredExpireDate', models.DateField()),
                ('featuredDate', models.DateField(auto_now_add=True)),
                ('isActive', models.BooleanField(db_index=True, default=True)),
                ('comId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='offernewsapp.Company')),
            ],
        ),
        migrations.CreateModel(
            name='FeaturedPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(choices=[('B', 'Cover_Big'), ('S', 'Cover_Small'), ('F', 'First_Page')], default='F', max_length=1)),
                ('featuredExpireDate', models.DateField()),
                ('featuredDate', models.DateField(auto_now_add=True)),
                ('isActive', models.BooleanField(db_index=True, default=True)),
                ('postId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offernewsapp.Post')),
            ],
        ),
        migrations.RemoveField(
            model_name='comfeaturepricing',
            name='featuredId',
        ),
        migrations.RemoveField(
            model_name='comfeaturepricing',
            name='postId',
        ),
        migrations.RemoveField(
            model_name='postfeaturepricing',
            name='featuredId',
        ),
        migrations.RemoveField(
            model_name='postfeaturepricing',
            name='postId',
        ),
        migrations.DeleteModel(
            name='Featured',
        ),
        migrations.AddField(
            model_name='featuredpost',
            name='priceId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offernewsapp.PostFeaturePricing'),
        ),
        migrations.AddField(
            model_name='featuredcom',
            name='priceId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offernewsapp.ComFeaturePricing'),
        ),
    ]
