# Generated by Django 2.1.2 on 2019-01-28 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('offernewsapp', '0005_auto_20190128_2100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='featuredpost',
            name='priceId',
        ),
        migrations.AlterField(
            model_name='featuredcom',
            name='comId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offernewsapp.Company'),
        ),
    ]
