# Generated by Django 2.1.2 on 2019-01-28 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offernewsapp', '0006_auto_20190128_2120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='externalad',
            name='price',
        ),
        migrations.AlterField(
            model_name='comfeaturepricing',
            name='position',
            field=models.CharField(choices=[('Company Page', 'Com_Page'), ('First Page', 'First_Page')], default='First Page', max_length=15),
        ),
        migrations.AlterField(
            model_name='externalad',
            name='position',
            field=models.CharField(choices=[('Popup', 'Popup'), ('Front Page', 'Front_Page')], default='Front Page', max_length=15),
        ),
        migrations.AlterField(
            model_name='externaladpricing',
            name='position',
            field=models.CharField(choices=[('Popup', 'Popup'), ('Front Page', 'Front_Page')], default='Front Page', max_length=15),
        ),
        migrations.AlterField(
            model_name='featuredcom',
            name='position',
            field=models.CharField(choices=[('Company Page', 'Com_Page'), ('First Page', 'First_Page')], default='First Page', max_length=15),
        ),
        migrations.AlterField(
            model_name='featuredpost',
            name='position',
            field=models.CharField(choices=[('Cover Big', 'Cover_Big'), ('Cover Small', 'Cover_Small'), ('First Page', 'First_Page')], default='First Page', max_length=15),
        ),
        migrations.AlterField(
            model_name='postfeaturepricing',
            name='position',
            field=models.CharField(choices=[('Cover Big', 'Cover_Big'), ('Cover Small', 'Cover_Small'), ('First Page', 'First_Page')], default='First Page', max_length=15),
        ),
    ]
