# Generated by Django 2.1.2 on 2019-02-07 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offernewsapp', '0011_auto_20190207_0625'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='badgeType',
            field=models.CharField(choices=[('N', 'New'), ('H', 'Hot'), ('E', 'Expired')], default='N', max_length=1),
        ),
    ]
