# Generated by Django 2.1.2 on 2019-02-12 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offernewsapp', '0013_auto_20190207_0644'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='featuredpost',
            name='postId',
        ),
        migrations.AddField(
            model_name='featuredpost',
            name='postId',
            field=models.ManyToManyField(to='offernewsapp.Post'),
        ),
    ]
