# Generated by Django 2.1.2 on 2019-02-12 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('offernewsapp', '0015_auto_20190212_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featuredpost',
            name='postId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postId', to='offernewsapp.Post'),
        ),
    ]
